name: Rassensystem
version: '1.21.5'
main: me.marc3308.rassensystem.Rassensystem
depend: [zerotrust]
api-version: 1.21.5

permissions:
  Spezienspezialist:
    description: you are a spezien specialist

commands:
  givespezies:
    description: gives you the spezies
    permission: Spezienspezialist
  spezieseditor:
    description: opens the spezien editor
    permission: Spezienspezialist